<div style="border-radius: 10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size: 100%; text-align: left">
    <font size="2px" color="#000000">
        <h2>Project Title: Sprint 2 - Feature Engineering</h2>
        <p>Author: Kouyu (Coco) Yang</p>  
        <p>Date Filed: Nov 9th, 2023</p>  
        <p>Contact: <a href="mailto:cocoyang526@gmail.com">cocoyang526@gmail.com</a></p>  
    </font>
</div>

## **Table of Contents**

<div style="border-radius: 10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size: 100%; text-align: left">
<font size="2px" color="#000000">
    
<a href="#part-1-project-introduction">Part 1 Project Introduction</a> <br>
<a href="#part-2-data-dictionary">Part 2 Data Dictionary</a> <br>
<a href="#part-3-feature-engineering">Part 3 Feature Engineering</a> <br>
  * <a href="#3.1-load-data">3.1 Load Data</a> <br>
  * <a href="#3.2-relabel-the-target-columns">3.2 Relabel the target columns</a> <br>
  * <a href="#3.3-label-encoding-of-the-target-columns">3.3 Label encoding of the target columns</a> <br>
  * <a href="#3.4-age-binning">3.4 Age Binning</a> <br>
  * <a href="#3.5-ordinal-encoding">3.5 Ordinal Encoding</a> <br>
  * <a href="#3.6-one-hot-encoding-binary-columns">3.6 One Hot Encoding - Binary Columns</a> <br>
  * <a href="#3.7-one-hot-encoding-get-dummies">3.7 One Hot Encoding - Get Dummies</a> <br>
  * <a href="#3.8-get-rid-of-reference-columns">3.8 Get rid of reference columns</a> <br>
  * <a href="#3.9-export-data-for-modelling">3.9 Export data for modelling</a> <br>
    
<div>

### **Part 1 Project Introduction**

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000">  


In this dedicated notebook, our focus narrows to the critical domain of feature engineering within our comprehensive Capstone project. Our primary objectives include:

- **Relabeling two target columns:** We apply the CDC score to questionnaire responses, transforming binary columns into multi-class categorical columns. This relabeling process distills the essence of self-reported mental health, providing us with valuable insights for our modeling phase.

- **Encoding techniques:** We meticulously apply various encoding methods to both target columns and independent features. These techniques include label encoding, ordinal encoding, and one-hot encoding. Through these methods, we convert qualitative attributes into quantitative insights, preparing our data for modeling and enabling our machine learning models to harness the rich information contained within these features.

By crafting this feature engineering notebook, we set the stage for the predictive power and actionable insights that lie ahead. Our efforts here enable us to better understand the intricate relationship between household factors and mental health, taking us one step closer to reducing the stigma surrounding mental well-being and empowering stakeholders with the tools to create a healthier, more resilient society. 
    
    
<div>

### **Part 2 Data Dictionary**

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">

| Column Name                  | Column Content                                      |
|-----------------------------|----------------------------------------------------|
| SCRAM                       | Unique identifier for each record.                 |
| Major Depressive Disorder   | Binary variable indicating presence or absence of Major Depressive Disorder. |
| Generalized Anxiety Disorder| Binary variable indicating presence or absence of Generalized Anxiety Disorder. |
| Anxiety Depression Diagnosis | Binary variable indicating presence or absence of an Anxiety Depression Diagnosis. |
| Birth Year                  | Year of birth of the individual.                   |
| Birth Gender                | Gender assigned at birth.                          |
| Gender Identity             | Gender identity of the individual.                 |
| Sexual Orientation          | Sexual orientation of the individual.              |
| Race/Hispanic Ethnicity     | Race or Hispanic ethnicity of the individual.      |
| Education                   | Highest level of education attained by the individual. |
| Marriage Status             | Marital status of the individual.                  |
| Work Loss                   | Information about work loss or employment status.  |
| Any Work                    | Indicates whether the individual is currently employed. |
| Unemployment Insurance Receive | Indicates whether the individual receives unemployment insurance. |
| Total People                | Total number of people in the individual's household. |
| Total Children              | Total number of children in the individual's household. |
| Price Change                | Information about changes in prices.               |
| Price Stress                | Indicates whether the individual experiences stress related to price changes. |
| Accommodation               | Type of accommodation the individual resides in.  |
| Income                      | Information about the individual's income.        |
| Food Spend                  | Amount spent on food.                               |
| Food Supply                 | Information about the availability of food.       |
| Medical Shortage            | Indicates whether the individual experiences shortages of medical supplies. |
| Active Duty                 | Indicates whether the individual is on active military duty. |
| Veteran                     | Indicates whether the individual is a military veteran. |
| Had Covid-19                | Indicates whether the individual had COVID-19.    |
| Covid Vaccinated            | Indicates whether the individual has received the COVID-19 vaccine. |
| Age                         | Age of the individual.                              |


<div>

### **Part 3 Feature Engineering**

#### **3.1 Load Data**

In [21]:
#load libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [22]:
#load the original dataset 
df_original = pd.read_csv('/Users/kouyuyang/Brainstation/Capstone/pulse2023_puf_61.csv')

#sanity check
df_original.head()

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,HWEIGHT,PWEIGHT,TBIRTH_YEAR,ABIRTH_YEAR,RHISPANIC,...,ND_MED,HLTH_MHCHLD1,HLTH_MHCHLD2,HLTH_MHCHLD3,HLTH_MHCHLD4,HLTH_MHCHLD5,HLTH_MHCHLD6,HLTH_MHCHLD7,HLTH_MHCHLD8,HLTH_MHCHLD9
0,V610000001,61,26,19820.0,3,1076.930201,1957.379888,1992,2,1,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
1,V610000002,61,6,31080.0,4,2418.728551,4644.401245,1939,2,1,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
2,V610000003,61,6,NaN,4,919.019106,882.342394,1960,2,1,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
3,V610000004,61,38,NaN,3,427.217423,1956.616232,1979,2,1,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
4,V610000005,61,40,NaN,2,2156.128147,4085.895811,2002,2,1,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88

In [23]:
#load the cleaned data from sprint 1 (Dataset after Feature Selection) 
df = pd.read_csv('/Users/kouyuyang/Brainstation/Capstone/Sprint 2/sprint_1_dataset.csv',index_col='SCRAM')

#Sanity Check
df.head()

,Major Depressive Disorder,Generalized Anxiety Disorder,Anxiety Depression Diagnosis,Birth Year,Birth Gender,Gender Indentity,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,...,Accommodation,Income,Food Spend,Food Supply,Medical Shortage,Active Duty,Veteran,Had Covid-19,Covid Vaccinated,Age
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Yes,Yes,Yes,1992,Female,Female,Bisexual,White,Graduate degree,Now married,...,Owned with mortgage,"$200,000 and above",200.0,Enough Food,No,No,No,No,Yes,31
V610000002,No,No,No,1939,Female,Female,Straight,White,some college/Associate's degree,Now married,...,Owned with mortgage,Unreported/Unknown,200.0,Enough Food,No,No,Spouse Served Active Duty,Yes,Yes,84
V610000003,Yes,Yes,Yes,1960,Male,Male,Straight,White,some college/Associate,Divorced,...,Fully Owned,"$75,000 - $99,999",200.0,Enough Food,No,No,No,No,Yes,63
V610000005,No,No,No,2002,Male,Male,Straight,White,some college/Associate,Never married,...,Unreported/Unknown,Unreported/Unknown,200.0,Unreported/Unknown,Yes,No,No,Yes,Yes,21
V610000006,Yes,Yes,Yes,1985,Male,Male,Straight,White,Graduate degree,Never married,...,Fully Owned,"$150,000 - $199,999",65.0,Enough Food,No,No,No,Yes,Yes,38

In [24]:
#check the columns and rows
df.shape

(62505, 27)

In [25]:
#check the missing values and datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62505 entries, V610000001 to V610068454
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Major Depressive Disorder       62505 non-null  object
 1   Generalized Anxiety Disorder    62505 non-null  object
 2   Anxiety Depression Diagnosis    62505 non-null  object
 3   Birth Year                      62505 non-null  int64
 4   Birth Gender                    62505 non-null  object
 5   Gender Indentity                62505 non-null  object
 6   Sexual orientation              62505 non-null  object
 7   Race/Hispanic ethnicity         62505 non-null  object
 8   Education                       62505 non-null  object
 9   Marriage status                 62505 non-null  object
 10  Work Loss                       62505 non-null  object
 11  Any Work                        62505 non-null  object
 12  Unemployment Insurance Receive  62505 non-null  object
 13  Total People                    62505 non-null  int64
 14  Total Children                  62505 non-null  int64
 15  Price Change                    62505 non-null  object
 16  Price Stress                    62505 non-null  object
 17  Accommodation                   62505 non-null  object
 18  Income                          62505 non-null  object
 19  Food Spend                      62505 non-null  float64
 20  Food Supply                     62505 non-null  object
 21  Medical Shortage                62505 non-null  object
 22  Active Duty                     62505 non-null  object
 23  Veteran                         62505 non-null  object
 24  Had Covid-19                    62505 non-null  object
 25  Covid Vaccinated                62505 non-null  object
 26  Age                             62505 non-null  int64
dtypes: float64(1), int64(4), object(22)
memory usage: 13.4+ MB

#### **3.2 Relabel the target columns**

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000">  
    <b>Reapply the scoring method on four feaures to get the two target columns</b>
    

In this project, we aim to enhance the granularity of our target columns, which initially consisted of binary labels "Yes" and "No," indicating the presence or absence of mental health issues. To better capture the nuances of mental health, we will restructure these binary labels into multiple classes, reflecting three distinct levels of mental health issues:

Depression:
- Sum the score of `INTEREST` and `DOWN`. If the score is >= 5, the anticipant is associated with diagnoses of major depressive disorder. 
- Sum the score of `INTEREST` and `DOWN`. If the score is >2 & < 5, the anticipant is associated with mild depressive disorder.
- Sum the score of `INTEREST` and `DOWN`. If the score is 2, the anticipant has no depression.

Anxiety:
- Sum the score of `ANXIOUS`  adn `WORRY`. If the score is >=5, the anticipant is associated with diagnoses of generalized anxiety disorder. 
- Sum the score of `ANXIOUS` and `WORRY`. If the score is >2 & <5, the anticipant is associated with mild anxiety disorder.
- Sum the score of `ANXIOUS` and `WORRY`. If the score is 2, the anticipant has no anxiety.

Reference can be found on : https://www.cdc.gov/nchs/covid19/pulse/mental-health.htm

<div>

**Relabel the Major Depressive Disorder column**

In [27]:
#get a copy dataframe from the original one
df2=df_original.copy()

#reset the index
df2.set_index("SCRAM",inplace=True)

#sanity check
df2.head()

,WEEK,EST_ST,EST_MSA,REGION,HWEIGHT,PWEIGHT,TBIRTH_YEAR,ABIRTH_YEAR,RHISPANIC,AHISPANIC,...,ND_MED,HLTH_MHCHLD1,HLTH_MHCHLD2,HLTH_MHCHLD3,HLTH_MHCHLD4,HLTH_MHCHLD5,HLTH_MHCHLD6,HLTH_MHCHLD7,HLTH_MHCHLD8,HLTH_MHCHLD9
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,61,26,19820.0,3,1076.930201,1957.379888,1992,2,1,2,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
V610000002,61,6,31080.0,4,2418.728551,4644.401245,1939,2,1,2,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
V610000003,61,6,NaN,4,919.019106,882.342394,1960,2,1,2,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
V610000004,61,38,NaN,3,427.217423,1956.616232,1979,2,1,2,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
V610000005,61,40,NaN,2,2156.128147,4085.895811,2002,2,1,2,...,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88

In [28]:
#create a list
four_features = ['INTEREST','DOWN','ANXIOUS','WORRY']

#make a loop to drop each feature of these four and update to dataframe df2
for feature in four_features:
    mask = df2[feature].isin([-88, -99])
    df2 = df2[~mask]

# Sum the score of 'INTEREST' and 'DOWN'. 
df2['PHQ2_Score_Sum']=df2['INTEREST']+df2['DOWN']

# Categorize 'Major Depressive Disorder'
df2['Depression'] = df2['PHQ2_Score_Sum'].apply(lambda x: 'No' if x == 2 else ('Mild Depression' if 2 < x < 5 else 'Major Depressive Disorder'))

# Sanity Check
df2['Depression'].value_counts()

No                           33883
Mild Depression              18665
Major Depressive Disorder     9957
Name: Depression, dtype: int64

**Relabel the Generalized Anxiety Disorder column**

In [29]:
# Sum the score of 'ANXIOUS' adn 'WORRY'. 
df2['GAD_Score_Sum'] = df2['ANXIOUS']+df2['WORRY']

#If the score is >=3, the anticipant is associated with diagnoses of generalized anxiety disorder.
df2['Anxiety']=df2['GAD_Score_Sum'].apply(lambda x: 'No' if x == 2 else ('Mild Anxiety' if 2 < x < 5 else 'Generalized Anxiety Disorder'))

# Sanity Check
df2['Anxiety'].value_counts()

No                              28181
Mild Anxiety                    20706
Generalized Anxiety Disorder    13618
Name: Anxiety, dtype: int64

In [30]:
# Sanity Check 
df2[['Depression','Anxiety']].head(10)

                           Depression                       Anxiety
SCRAM
V610000001  Major Depressive Disorder                  Mild Anxiety
V610000002                         No                            No
V610000003  Major Depressive Disorder  Generalized Anxiety Disorder
V610000005                         No                            No
V610000006            Mild Depression                  Mild Anxiety
V610000007                         No                            No
V610000008  Major Depressive Disorder  Generalized Anxiety Disorder
V610000009                         No  Generalized Anxiety Disorder
V610000010  Major Depressive Disorder                  Mild Anxiety
V610000011            Mild Depression                  Mild Anxiety

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000"> 
    <b>Comment</b>: Excellent! We have successfully got two new target columns with three classes for each. Now we need to copy these two columns to our target dataframe df and drop the two old ones. 
<div>

In [31]:
# Get new target columns from df2
df.loc[:, 'Depression'] = df2.loc[:,'Depression'].copy()
df.loc[:,'Anxiety'] = df2.loc[:,'Anxiety'].copy()

#Drop the previous target columns
df.drop(columns = ['Major Depressive Disorder','Generalized Anxiety Disorder','Anxiety Depression Diagnosis'],inplace=True)

# Sanity Check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62505 entries, V610000001 to V610068454
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Birth Year                      62505 non-null  int64
 1   Birth Gender                    62505 non-null  object
 2   Gender Indentity                62505 non-null  object
 3   Sexual orientation              62505 non-null  object
 4   Race/Hispanic ethnicity         62505 non-null  object
 5   Education                       62505 non-null  object
 6   Marriage status                 62505 non-null  object
 7   Work Loss                       62505 non-null  object
 8   Any Work                        62505 non-null  object
 9   Unemployment Insurance Receive  62505 non-null  object
 10  Total People                    62505 non-null  int64
 11  Total Children                  62505 non-null  int64
 12  Price Change                    62505 non-null  object
 13  Price Stress                    62505 non-null  object
 14  Accommodation                   62505 non-null  object
 15  Income                          62505 non-null  object
 16  Food Spend                      62505 non-null  float64
 17  Food Supply                     62505 non-null  object
 18  Medical Shortage                62505 non-null  object
 19  Active Duty                     62505 non-null  object
 20  Veteran                         62505 non-null  object
 21  Had Covid-19                    62505 non-null  object
 22  Covid Vaccinated                62505 non-null  object
 23  Age                             62505 non-null  int64
 24  Depression                      62505 non-null  object
 25  Anxiety                         62505 non-null  object
dtypes: float64(1), int64(4), object(21)
memory usage: 12.9+ MB

#### **3.3 Label encoding of the target columns**

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000"> 
To prepare our target columns for modeling, we will transform categorical labels into numeric values using the LabelEncoder. This conversion will enable our machine learning models to work with numerical representations of the target classes.
<div>

In [368]:
from sklearn.preprocessing import LabelEncoder
#Instantiate the model
le=LabelEncoder()

#transform the columns
df['Depression_encoded'] = le.fit_transform(df['Depression'])
df['Anxiety_encoded'] = le.fit_transform(df['Anxiety'])

#Sanity Check
df['Depression_encoded'].value_counts()

2    33883
1    18665
0     9957
Name: Depression_encoded, dtype: int64

In [370]:
#drop the old categorical columns 
df.drop(columns=['Depression','Anxiety'],inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62505 entries, V610000001 to V610068454
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Birth Year                      62505 non-null  int64
 1   Birth Gender                    62505 non-null  object
 2   Gender Indentity                62505 non-null  object
 3   Sexual orientation              62505 non-null  object
 4   Race/Hispanic ethnicity         62505 non-null  object
 5   Education                       62505 non-null  object
 6   Marriage status                 62505 non-null  object
 7   Work Loss                       62505 non-null  object
 8   Any Work                        62505 non-null  object
 9   Unemployment Insurance Receive  62505 non-null  object
 10  Total People                    62505 non-null  int64
 11  Total Children                  62505 non-null  int64
 12  Price Change                    62505 non-null  object
 13  Price Stress                    62505 non-null  object
 14  Accommodation                   62505 non-null  object
 15  Income                          62505 non-null  object
 16  Food Spend                      62505 non-null  float64
 17  Food Supply                     62505 non-null  object
 18  Medical Shortage                62505 non-null  object
 19  Active Duty                     62505 non-null  object
 20  Veteran                         62505 non-null  object
 21  Had Covid-19                    62505 non-null  object
 22  Covid Vaccinated                62505 non-null  object
 23  Age                             62505 non-null  int64
 24  Depression_encoded              62505 non-null  int64
 25  Anxiety_encoded                 62505 non-null  int64
dtypes: float64(1), int64(6), object(19)
memory usage: 12.9+ MB

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000"> 
    <b>Comment:</b> With the target columns now represented as numerical values, our focus shifts to the independent features. Our initial step involves binning the `Age` variable to create more meaningful age groups.
<div>

#### **3.4 Age Binning**

In [371]:
#check the age statistics
df['Age'].describe()

count    62505.000000
mean        52.061131
std         15.804197
min         18.000000
25%         39.000000
50%         52.000000
75%         65.000000
max         88.000000
Name: Age, dtype: float64

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000"> 
    <b>Age Binning Categories:</b>

- **Greatest-Silent Generation:** This generation includes those born before 1946.
Approximate ages: 76 years old and older (as of 2022).

- **Baby Boomers (Boomer):** Baby Boomers were born in the post-World War II baby boom years.
Approximate ages: 57 to 75 years old (as of 2022).

- **Generation X (GenX):** Generation X represents the generation born after the Baby Boomers.
Approximate ages: 41 to 56 years old (as of 2022).

- **Millennials:** Millennials, also known as Generation Y, were born in the 1980s and 1990s.
Approximate ages: 26 to 40 years old (as of 2022).

- **Generation Z (GenZ):** Generation Z represents the youngest generation.
Approximate ages: 25 years old and younger (as of 2022).
<div>

In [32]:
# Define a function to categorize age into generational groups
def categorize_generations(age):
    if age >= 76:
        return 'Greatest-Silent Generation'
    elif 57 <= age <= 75:
        return 'Baby Boomers'
    elif 41 <= age <= 56:
        return 'Generation X'
    elif 26 <= age <= 40:
        return 'Millennials'
    else:
        return 'Generation Z'

# Apply the function to create a new column for generational groups
df['Age Generation'] = df['Age'].apply(categorize_generations)

# Sanity Check
df['Age Generation'].value_counts()

Baby Boomers                  22672
Generation X                  18495
Millennials                   15465
Greatest-Silent Generation     3782
Generation Z                   2091
Name: Age Generation, dtype: int64

In [33]:
#drop the birth year and age columns since we used birth year column to get the age in previous notebook
df.drop(columns = ['Birth Year','Age'],inplace=True)

#Sanity Check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62505 entries, V610000001 to V610068454
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Birth Gender                    62505 non-null  object
 1   Gender Indentity                62505 non-null  object
 2   Sexual orientation              62505 non-null  object
 3   Race/Hispanic ethnicity         62505 non-null  object
 4   Education                       62505 non-null  object
 5   Marriage status                 62505 non-null  object
 6   Work Loss                       62505 non-null  object
 7   Any Work                        62505 non-null  object
 8   Unemployment Insurance Receive  62505 non-null  object
 9   Total People                    62505 non-null  int64
 10  Total Children                  62505 non-null  int64
 11  Price Change                    62505 non-null  object
 12  Price Stress                    62505 non-null  object
 13  Accommodation                   62505 non-null  object
 14  Income                          62505 non-null  object
 15  Food Spend                      62505 non-null  float64
 16  Food Supply                     62505 non-null  object
 17  Medical Shortage                62505 non-null  object
 18  Active Duty                     62505 non-null  object
 19  Veteran                         62505 non-null  object
 20  Had Covid-19                    62505 non-null  object
 21  Covid Vaccinated                62505 non-null  object
 22  Depression                      62505 non-null  object
 23  Anxiety                         62505 non-null  object
 24  Age Generation                  62505 non-null  object
dtypes: float64(1), int64(2), object(22)
memory usage: 12.4+ MB

#### **3.5 Ordinal Encoding**

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000"> 

Ordinal encoding is applied to columns such as income, education, and age generation to capture the inherent hierarchy and logical order of these categories. By assigning numeric values that reflect the increasing order within each feature, our machine learning models can effectively leverage this structured information for improved predictions. This encoding technique enhances both the interpretability and predictive performance of our models.
    
<div>

`Income`

In [34]:
df['Income'].value_counts()

$100,000 - $149,999    10128
$50,000 - $74,999       9043
Unreported/Unknown      7921
$75,000 - $99,999       7785
$200,000 and above      6718
$35,000 - $49,999       5702
$150,000 - $199,999     5379
Less than $25,000       5344
$25,000 - $34,999       4485
Name: Income, dtype: int64

In [35]:
#check the percentage of Unreported/Unknown
pct = (df['Income']=='Unreported/Unknown').sum() / df.shape[0]
print(f'The missing value percentage is :{pct*100}%')

The missing value percentage is :12.672586193104552%

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000"> 
    <b>Comment</b>: We may need to drop the rows with Unknown values since the missing percentage is below 15% and our ordinal encoder does not work well with unknown values.
<div>

In [36]:
# drop rows where income has unreported/unknown rows 
df = df[df['Income'] != 'Unreported/Unknown']

#sanity check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54584 entries, V610000001 to V610068454
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Birth Gender                    54584 non-null  object
 1   Gender Indentity                54584 non-null  object
 2   Sexual orientation              54584 non-null  object
 3   Race/Hispanic ethnicity         54584 non-null  object
 4   Education                       54584 non-null  object
 5   Marriage status                 54584 non-null  object
 6   Work Loss                       54584 non-null  object
 7   Any Work                        54584 non-null  object
 8   Unemployment Insurance Receive  54584 non-null  object
 9   Total People                    54584 non-null  int64
 10  Total Children                  54584 non-null  int64
 11  Price Change                    54584 non-null  object
 12  Price Stress                    54584 non-null  object
 13  Accommodation                   54584 non-null  object
 14  Income                          54584 non-null  object
 15  Food Spend                      54584 non-null  float64
 16  Food Supply                     54584 non-null  object
 17  Medical Shortage                54584 non-null  object
 18  Active Duty                     54584 non-null  object
 19  Veteran                         54584 non-null  object
 20  Had Covid-19                    54584 non-null  object
 21  Covid Vaccinated                54584 non-null  object
 22  Depression                      54584 non-null  object
 23  Anxiety                         54584 non-null  object
 24  Age Generation                  54584 non-null  object
dtypes: float64(1), int64(2), object(22)
memory usage: 10.8+ MB

In [37]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Less than $25,000', '$25,000 - $34,999', '$35,000 - $49,999', '$50,000 - $74,999', '$75,000 - $99,999','$100,000 - $149,999','$150,000 - $199,999','$200,000 and above']])
oe.fit_transform(pd.DataFrame(df['Income']))

#transform
df['Income'] = oe.transform(df['Income'].values.reshape(-1,1))

#sanity check
df['Income'].value_counts()

/Users/kouyuyang/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

5.0    10128
3.0     9043
4.0     7785
7.0     6718
2.0     5702
6.0     5379
0.0     5344
1.0     4485
Name: Income, dtype: int64

`Age Generation`

In [38]:
df['Age Generation'].value_counts()

Baby Boomers                  20059
Generation X                  16222
Millennials                   13459
Greatest-Silent Generation     3287
Generation Z                   1557
Name: Age Generation, dtype: int64

In [39]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Generation Z', 'Millennials', 'Generation X', 'Baby Boomers', 'Greatest-Silent Generation']])
oe.fit_transform(pd.DataFrame(df['Age Generation']))

array([[1.],
       [3.],
       [1.],
       ...,
       [3.],
       [2.],
       [2.]])

In [40]:
#check the categories
oe.categories_

[array(['Generation Z', 'Millennials', 'Generation X', 'Baby Boomers',
        'Greatest-Silent Generation'], dtype=object)]

In [41]:
#transform
df['Age Generation'] = oe.transform(df['Age Generation'].values.reshape(-1,1))

#sanity check the encoded numbers
df['Age Generation'].value_counts()

/Users/kouyuyang/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

3.0    20059
2.0    16222
1.0    13459
4.0     3287
0.0     1557
Name: Age Generation, dtype: int64

In [42]:
# Visualize the categories and their encoded numbers
encoded_categories = pd.DataFrame({
    'Category': oe.categories_[0],
    'Encoded Number': range(len(oe.categories_[0]))
})

# Display the table
print(encoded_categories)

                     Category  Encoded Number
0                Generation Z               0
1                 Millennials               1
2                Generation X               2
3                Baby Boomers               3
4  Greatest-Silent Generation               4

`Education`

In [43]:
df['Education'].value_counts()

Bachelor degree                    15776
Graduate degree                    14158
some college/Associate             11387
High school or GED                  7192
some college/Associate's degree     5739
Less than high school                332
Name: Education, dtype: int64

In [44]:
#Instantiate the model

oe = OrdinalEncoder(categories=[['Less than high school', "some college/Associate's degree", 'High school or GED', 'some college/Associate', 'Graduate degree','Bachelor degree']])
#Fit and transform
oe.fit_transform(pd.DataFrame(df['Education']))

array([[4.],
       [3.],
       [4.],
       ...,
       [4.],
       [5.],
       [5.]])

In [45]:
#check the categories
oe.categories_

[array(['Less than high school', "some college/Associate's degree",
        'High school or GED', 'some college/Associate', 'Graduate degree',
        'Bachelor degree'], dtype=object)]

In [46]:
#transform
df['Education'] = oe.transform(df['Education'].values.reshape(-1,1))

#sanity check the encoded numbers
df['Education'].value_counts()

/Users/kouyuyang/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

5.0    15776
4.0    14158
3.0    11387
2.0     7192
1.0     5739
0.0      332
Name: Education, dtype: int64

In [47]:
#Instantiate the model
enc = OrdinalEncoder()

#Fit the model
X = df['Education'].values.reshape(-1,1)
enc.fit(X)

#sanity check the category names
enc.categories_

[array([0., 1., 2., 3., 4., 5.])]

In [48]:
# Visualize the categories and their encoded numbers
encoded_categories = pd.DataFrame({
    'Category': oe.categories_[0],
    'Encoded Number': range(len(oe.categories_[0]))
})

# Display the table
print(encoded_categories)

                          Category  Encoded Number
0            Less than high school               0
1  some college/Associate's degree               1
2               High school or GED               2
3           some college/Associate               3
4                  Graduate degree               4
5                  Bachelor degree               5

#### **3.6 One Hot Encoding - Binary Columns**

In [49]:
df.head()

,Birth Gender,Gender Indentity,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,Work Loss,Any Work,Unemployment Insurance Receive,Total People,...,Food Spend,Food Supply,Medical Shortage,Active Duty,Veteran,Had Covid-19,Covid Vaccinated,Depression,Anxiety,Age Generation
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Female,Female,Bisexual,White,4.0,Now married,No,Yes,No,2,...,200.0,Enough Food,No,No,No,No,Yes,Major Depressive Disorder,Mild Anxiety,1.0
V610000003,Male,Male,Straight,White,3.0,Divorced,Yes,No,No,1,...,200.0,Enough Food,No,No,No,No,Yes,Major Depressive Disorder,Generalized Anxiety Disorder,3.0
V610000006,Male,Male,Straight,White,4.0,Never married,No,Yes,No,1,...,65.0,Enough Food,No,No,No,Yes,Yes,Mild Depression,Mild Anxiety,1.0
V610000007,Female,Female,Straight,Other,2.0,Never married,No,Yes,No,4,...,200.0,Sometimes Not Enough,No,No,No,Yes,No,No,No,2.0
V610000008,Male,Male,Straight,White,4.0,Now married,No,Yes,No,2,...,300.0,Enough Food,No,No,No,Yes,Yes,Major Depressive Disorder,Generalized Anxiety Disorder,1.0

`Medical Shortage`

In [50]:
#create a new dataframe 
df_with_dummies=df.copy()
df_with_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54584 entries, V610000001 to V610068454
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Birth Gender                    54584 non-null  object
 1   Gender Indentity                54584 non-null  object
 2   Sexual orientation              54584 non-null  object
 3   Race/Hispanic ethnicity         54584 non-null  object
 4   Education                       54584 non-null  float64
 5   Marriage status                 54584 non-null  object
 6   Work Loss                       54584 non-null  object
 7   Any Work                        54584 non-null  object
 8   Unemployment Insurance Receive  54584 non-null  object
 9   Total People                    54584 non-null  int64
 10  Total Children                  54584 non-null  int64
 11  Price Change                    54584 non-null  object
 12  Price Stress                    54584 non-null  object
 13  Accommodation                   54584 non-null  object
 14  Income                          54584 non-null  float64
 15  Food Spend                      54584 non-null  float64
 16  Food Supply                     54584 non-null  object
 17  Medical Shortage                54584 non-null  object
 18  Active Duty                     54584 non-null  object
 19  Veteran                         54584 non-null  object
 20  Had Covid-19                    54584 non-null  object
 21  Covid Vaccinated                54584 non-null  object
 22  Depression                      54584 non-null  object
 23  Anxiety                         54584 non-null  object
 24  Age Generation                  54584 non-null  float64
dtypes: float64(4), int64(2), object(19)
memory usage: 10.8+ MB

In [51]:
df_with_dummies['Medical Shortage'].value_counts()

No     43936
Yes    10648
Name: Medical Shortage, dtype: int64

In [52]:
#assign to binary values of 0 and 1 
df_with_dummies['Medical Shortage'] = df_with_dummies['Medical Shortage'].map({'No': 0,'Yes':1})
                                                      
#Sanity Check
df_with_dummies['Medical Shortage'].value_counts()

0    43936
1    10648
Name: Medical Shortage, dtype: int64

#### **3.7 One Hot Encoding - Get Dummies**

`Work Loss`

In [53]:
df_with_dummies['Work Loss'].value_counts()

No                     49899
Yes                     4593
Unreported/Unknown        92
Name: Work Loss, dtype: int64

In [54]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Work Loss'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Birth Gender,Gender Indentity,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,Any Work,Unemployment Insurance Receive,Total People,Total Children,...,Active Duty,Veteran,Had Covid-19,Covid Vaccinated,Depression,Anxiety,Age Generation,Work Loss_No,Work Loss_Unreported/Unknown,Work Loss_Yes
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Female,Female,Bisexual,White,4.0,Now married,Yes,No,2,0,...,No,No,No,Yes,Major Depressive Disorder,Mild Anxiety,1.0,1,0,0
V610000003,Male,Male,Straight,White,3.0,Divorced,No,No,1,0,...,No,No,No,Yes,Major Depressive Disorder,Generalized Anxiety Disorder,3.0,0,0,1
V610000006,Male,Male,Straight,White,4.0,Never married,Yes,No,1,0,...,No,No,Yes,Yes,Mild Depression,Mild Anxiety,1.0,1,0,0
V610000007,Female,Female,Straight,Other,2.0,Never married,Yes,No,4,1,...,No,No,Yes,No,No,No,2.0,1,0,0
V610000008,Male,Male,Straight,White,4.0,Now married,Yes,No,2,0,...,No,No,Yes,Yes,Major Depressive Disorder,Generalized Anxiety Disorder,1.0,1,0,0

`Any Work`

In [55]:
df_with_dummies['Any Work'].value_counts()

Yes                    34127
No                     20333
Unreported/Unknown       124
Name: Any Work, dtype: int64

In [56]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Any Work'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Birth Gender,Gender Indentity,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,Unemployment Insurance Receive,Total People,Total Children,Price Change,...,Covid Vaccinated,Depression,Anxiety,Age Generation,Work Loss_No,Work Loss_Unreported/Unknown,Work Loss_Yes,Any Work_No,Any Work_Unreported/Unknown,Any Work_Yes
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Female,Female,Bisexual,White,4.0,Now married,No,2,0,Increased,...,Yes,Major Depressive Disorder,Mild Anxiety,1.0,1,0,0,0,0,1
V610000003,Male,Male,Straight,White,3.0,Divorced,No,1,0,Increased,...,Yes,Major Depressive Disorder,Generalized Anxiety Disorder,3.0,0,0,1,1,0,0
V610000006,Male,Male,Straight,White,4.0,Never married,No,1,0,Not changed,...,Yes,Mild Depression,Mild Anxiety,1.0,1,0,0,0,0,1
V610000007,Female,Female,Straight,Other,2.0,Never married,No,4,1,Increased,...,No,No,No,2.0,1,0,0,0,0,1
V610000008,Male,Male,Straight,White,4.0,Now married,No,2,0,Increased,...,Yes,Major Depressive Disorder,Generalized Anxiety Disorder,1.0,1,0,0,0,0,1

`Unemployement Insurance Receive`

In [57]:
df_with_dummies['Unemployment Insurance Receive'].value_counts()

No                     53888
Yes                      590
Unreported/Unknown       106
Name: Unemployment Insurance Receive, dtype: int64

In [58]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Unemployment Insurance Receive'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Birth Gender,Gender Indentity,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,Total People,Total Children,Price Change,Price Stress,...,Age Generation,Work Loss_No,Work Loss_Unreported/Unknown,Work Loss_Yes,Any Work_No,Any Work_Unreported/Unknown,Any Work_Yes,Unemployment Insurance Receive_No,Unemployment Insurance Receive_Unreported/Unknown,Unemployment Insurance Receive_Yes
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Female,Female,Bisexual,White,4.0,Now married,2,0,Increased,Very stressful,...,1.0,1,0,0,0,0,1,1,0,0
V610000003,Male,Male,Straight,White,3.0,Divorced,1,0,Increased,Very stressful,...,3.0,0,0,1,1,0,0,1,0,0
V610000006,Male,Male,Straight,White,4.0,Never married,1,0,Not changed,Unreported/Unknown,...,1.0,1,0,0,0,0,1,1,0,0
V610000007,Female,Female,Straight,Other,2.0,Never married,4,1,Increased,A little stressful,...,2.0,1,0,0,0,0,1,1,0,0
V610000008,Male,Male,Straight,White,4.0,Now married,2,0,Increased,Very stressful,...,1.0,1,0,0,0,0,1,1,0,0

`Had Covid-19`

In [59]:
df_with_dummies['Had Covid-19'].value_counts()

Yes                   30980
No                    23304
Unreported/Unknown      300
Name: Had Covid-19, dtype: int64

In [60]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Had Covid-19'],dtype = int)

#check the first five rows
df_with_dummies.head()

,Birth Gender,Gender Indentity,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,Total People,Total Children,Price Change,Price Stress,...,Work Loss_Yes,Any Work_No,Any Work_Unreported/Unknown,Any Work_Yes,Unemployment Insurance Receive_No,Unemployment Insurance Receive_Unreported/Unknown,Unemployment Insurance Receive_Yes,Had Covid-19_No,Had Covid-19_Unreported/Unknown,Had Covid-19_Yes
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Female,Female,Bisexual,White,4.0,Now married,2,0,Increased,Very stressful,...,0,0,0,1,1,0,0,1,0,0
V610000003,Male,Male,Straight,White,3.0,Divorced,1,0,Increased,Very stressful,...,1,1,0,0,1,0,0,1,0,0
V610000006,Male,Male,Straight,White,4.0,Never married,1,0,Not changed,Unreported/Unknown,...,0,0,0,1,1,0,0,0,0,1
V610000007,Female,Female,Straight,Other,2.0,Never married,4,1,Increased,A little stressful,...,0,0,0,1,1,0,0,0,0,1
V610000008,Male,Male,Straight,White,4.0,Now married,2,0,Increased,Very stressful,...,0,0,0,1,1,0,0,0,0,1

`Covid Vaccinated`

In [61]:
df_with_dummies['Covid Vaccinated'].value_counts()

Yes                   47714
No                     6634
Unreported/Unknown      236
Name: Covid Vaccinated, dtype: int64

In [62]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Covid Vaccinated'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Birth Gender,Gender Indentity,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,Total People,Total Children,Price Change,Price Stress,...,Any Work_Yes,Unemployment Insurance Receive_No,Unemployment Insurance Receive_Unreported/Unknown,Unemployment Insurance Receive_Yes,Had Covid-19_No,Had Covid-19_Unreported/Unknown,Had Covid-19_Yes,Covid Vaccinated_No,Covid Vaccinated_Unreported/Unknown,Covid Vaccinated_Yes
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Female,Female,Bisexual,White,4.0,Now married,2,0,Increased,Very stressful,...,1,1,0,0,1,0,0,0,0,1
V610000003,Male,Male,Straight,White,3.0,Divorced,1,0,Increased,Very stressful,...,0,1,0,0,1,0,0,0,0,1
V610000006,Male,Male,Straight,White,4.0,Never married,1,0,Not changed,Unreported/Unknown,...,1,1,0,0,0,0,1,0,0,1
V610000007,Female,Female,Straight,Other,2.0,Never married,4,1,Increased,A little stressful,...,1,1,0,0,0,0,1,1,0,0
V610000008,Male,Male,Straight,White,4.0,Now married,2,0,Increased,Very stressful,...,1,1,0,0,0,0,1,0,0,1

`Birth Gender`

In [63]:
df_with_dummies.drop(columns='Birth Gender',inplace=True)

`Gender Identity`

In [64]:
#Rename the column
df_with_dummies.rename(columns={'Gender Indentity':'Gender Identity'},inplace=True)

#check the value counts
df_with_dummies['Gender Identity'].value_counts()

Female                29684
Male                  23172
Unreported/Unknown      783
None of these           761
Transgender             184
Name: Gender Identity, dtype: int64

In [65]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Gender Identity'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Sexual orientation,Race/Hispanic ethnicity,Education,Marriage status,Total People,Total Children,Price Change,Price Stress,Accommodation,Income,...,Had Covid-19_Unreported/Unknown,Had Covid-19_Yes,Covid Vaccinated_No,Covid Vaccinated_Unreported/Unknown,Covid Vaccinated_Yes,Gender Identity_Female,Gender Identity_Male,Gender Identity_None of these,Gender Identity_Transgender,Gender Identity_Unreported/Unknown
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,Bisexual,White,4.0,Now married,2,0,Increased,Very stressful,Owned with mortgage,7.0,...,0,0,0,0,1,1,0,0,0,0
V610000003,Straight,White,3.0,Divorced,1,0,Increased,Very stressful,Fully Owned,4.0,...,0,0,0,0,1,0,1,0,0,0
V610000006,Straight,White,4.0,Never married,1,0,Not changed,Unreported/Unknown,Fully Owned,6.0,...,0,1,0,0,1,0,1,0,0,0
V610000007,Straight,Other,2.0,Never married,4,1,Increased,A little stressful,Rented,0.0,...,0,1,1,0,0,1,0,0,0,0
V610000008,Straight,White,4.0,Now married,2,0,Increased,Very stressful,Rented,6.0,...,0,1,0,0,1,0,1,0,0,0

`Sexual orientation`

In [66]:
#check the value counts
df_with_dummies['Sexual orientation'].value_counts()

Straight              48126
Bisexual               2490
Gay or lesbian         1923
Unreported/Unknown     1134
Something else          911
Name: Sexual orientation, dtype: int64

In [67]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Sexual orientation'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Race/Hispanic ethnicity,Education,Marriage status,Total People,Total Children,Price Change,Price Stress,Accommodation,Income,Food Spend,...,Gender Identity_Female,Gender Identity_Male,Gender Identity_None of these,Gender Identity_Transgender,Gender Identity_Unreported/Unknown,Sexual orientation_Bisexual,Sexual orientation_Gay or lesbian,Sexual orientation_Something else,Sexual orientation_Straight,Sexual orientation_Unreported/Unknown
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,White,4.0,Now married,2,0,Increased,Very stressful,Owned with mortgage,7.0,200.0,...,1,0,0,0,0,1,0,0,0,0
V610000003,White,3.0,Divorced,1,0,Increased,Very stressful,Fully Owned,4.0,200.0,...,0,1,0,0,0,0,0,0,1,0
V610000006,White,4.0,Never married,1,0,Not changed,Unreported/Unknown,Fully Owned,6.0,65.0,...,0,1,0,0,0,0,0,0,1,0
V610000007,Other,2.0,Never married,4,1,Increased,A little stressful,Rented,0.0,200.0,...,1,0,0,0,0,0,0,0,1,0
V610000008,White,4.0,Now married,2,0,Increased,Very stressful,Rented,6.0,300.0,...,0,1,0,0,0,0,0,0,1,0

`Race/Hispanic ethnicity`

In [68]:
#check the value counts
df_with_dummies['Race/Hispanic ethnicity'].value_counts()

White       41630
Hispanic     4575
Black        3732
Asian        2400
Other        2247
Name: Race/Hispanic ethnicity, dtype: int64

In [69]:
#create dummies for the Work Loss column
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Race/Hispanic ethnicity'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Education,Marriage status,Total People,Total Children,Price Change,Price Stress,Accommodation,Income,Food Spend,Food Supply,...,Sexual orientation_Bisexual,Sexual orientation_Gay or lesbian,Sexual orientation_Something else,Sexual orientation_Straight,Sexual orientation_Unreported/Unknown,Race/Hispanic ethnicity_Asian,Race/Hispanic ethnicity_Black,Race/Hispanic ethnicity_Hispanic,Race/Hispanic ethnicity_Other,Race/Hispanic ethnicity_White
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,4.0,Now married,2,0,Increased,Very stressful,Owned with mortgage,7.0,200.0,Enough Food,...,1,0,0,0,0,0,0,0,0,1
V610000003,3.0,Divorced,1,0,Increased,Very stressful,Fully Owned,4.0,200.0,Enough Food,...,0,0,0,1,0,0,0,0,0,1
V610000006,4.0,Never married,1,0,Not changed,Unreported/Unknown,Fully Owned,6.0,65.0,Enough Food,...,0,0,0,1,0,0,0,0,0,1
V610000007,2.0,Never married,4,1,Increased,A little stressful,Rented,0.0,200.0,Sometimes Not Enough,...,0,0,0,1,0,0,0,0,1,0
V610000008,4.0,Now married,2,0,Increased,Very stressful,Rented,6.0,300.0,Enough Food,...,0,0,0,1,0,0,0,0,0,1

`Marriage status`,`Price Change`,`Price Stress`,`Accommodation `

In [70]:
#create dummies
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Marriage status'],dtype=int)
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Price Change'],dtype=int)
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Price Stress'],dtype=int)
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Accommodation'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Education,Total People,Total Children,Income,Food Spend,Food Supply,Medical Shortage,Active Duty,Veteran,Depression,...,Price Stress_A little stressful,Price Stress_Moderately stressful,Price Stress_Not at all stressful,Price Stress_Unreported/Unknown,Price Stress_Very stressful,Accommodation_Fully Owned,Accommodation_Occupied without rent,Accommodation_Owned with mortgage,Accommodation_Rented,Accommodation_Unreported/Unknown
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,4.0,2,0,7.0,200.0,Enough Food,0,No,No,Major Depressive Disorder,...,0,0,0,0,1,0,0,1,0,0
V610000003,3.0,1,0,4.0,200.0,Enough Food,0,No,No,Major Depressive Disorder,...,0,0,0,0,1,1,0,0,0,0
V610000006,4.0,1,0,6.0,65.0,Enough Food,0,No,No,Mild Depression,...,0,0,0,1,0,1,0,0,0,0
V610000007,2.0,4,1,0.0,200.0,Sometimes Not Enough,0,No,No,No,...,1,0,0,0,0,0,0,0,1,0
V610000008,4.0,2,0,6.0,300.0,Enough Food,0,No,No,Major Depressive Disorder,...,0,0,0,0,1,0,0,0,1,0

`Food Supply`,`Active Duty`,`Veteran`

In [71]:
#create dummies
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Food Supply'],dtype=int)
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Active Duty'],dtype=int)
df_with_dummies = pd.get_dummies(data=df_with_dummies,columns=['Veteran'],dtype=int)

#check the first five rows
df_with_dummies.head()

,Education,Total People,Total Children,Income,Food Spend,Medical Shortage,Depression,Anxiety,Age Generation,Work Loss_No,...,Food Supply_Sometimes Not Enough,Food Supply_Unreported/Unknown,Active Duty_No,Active Duty_On Active Duty,Active Duty_Spouse On Active Duty,Active Duty_Unreported/Unknown,Veteran_No,Veteran_Served Active Duty,Veteran_Spouse Served Active Duty,Veteran_Unreported/Unknown
SCRAM,,,,,,,,,,,,,,,,,,,,,
V610000001,4.0,2,0,7.0,200.0,0,Major Depressive Disorder,Mild Anxiety,1.0,1,...,0,0,1,0,0,0,1,0,0,0
V610000003,3.0,1,0,4.0,200.0,0,Major Depressive Disorder,Generalized Anxiety Disorder,3.0,0,...,0,0,1,0,0,0,1,0,0,0
V610000006,4.0,1,0,6.0,65.0,0,Mild Depression,Mild Anxiety,1.0,1,...,0,0,1,0,0,0,1,0,0,0
V610000007,2.0,4,1,0.0,200.0,0,No,No,2.0,1,...,1,0,1,0,0,0,1,0,0,0
V610000008,4.0,2,0,6.0,300.0,0,Major Depressive Disorder,Generalized Anxiety Disorder,1.0,1,...,0,0,1,0,0,0,1,0,0,0

In [72]:
df_with_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54584 entries, V610000001 to V610068454
Data columns (total 71 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Education                                           54584 non-null  float64
 1   Total People                                        54584 non-null  int64
 2   Total Children                                      54584 non-null  int64
 3   Income                                              54584 non-null  float64
 4   Food Spend                                          54584 non-null  float64
 5   Medical Shortage                                    54584 non-null  int64
 6   Depression                                          54584 non-null  object
 7   Anxiety                                             54584 non-null  object
 8   Age Generation                                      54584 non-null  float64
 9   Work Loss_No                                        54584 non-null  int64
 10  Work Loss_Unreported/Unknown                        54584 non-null  int64
 11  Work Loss_Yes                                       54584 non-null  int64
 12  Any Work_No                                         54584 non-null  int64
 13  Any Work_Unreported/Unknown                         54584 non-null  int64
 14  Any Work_Yes                                        54584 non-null  int64
 15  Unemployment Insurance Receive_No                   54584 non-null  int64
 16  Unemployment Insurance Receive_Unreported/Unknown   54584 non-null  int64
 17  Unemployment Insurance Receive_Yes                  54584 non-null  int64
 18  Had Covid-19_No                                     54584 non-null  int64
 19  Had Covid-19_Unreported/Unknown                     54584 non-null  int64
 20  Had Covid-19_Yes                                    54584 non-null  int64
 21  Covid Vaccinated_No                                 54584 non-null  int64
 22  Covid Vaccinated_Unreported/Unknown                 54584 non-null  int64
 23  Covid Vaccinated_Yes                                54584 non-null  int64
 24  Gender Identity_Female                              54584 non-null  int64
 25  Gender Identity_Male                                54584 non-null  int64
 26  Gender Identity_None of these                       54584 non-null  int64
 27  Gender Identity_Transgender                         54584 non-null  int64
 28  Gender Identity_Unreported/Unknown                  54584 non-null  int64
 29  Sexual orientation_Bisexual                         54584 non-null  int64
 30  Sexual orientation_Gay or lesbian                   54584 non-null  int64
 31  Sexual orientation_Something else                   54584 non-null  int64
 32  Sexual orientation_Straight                         54584 non-null  int64
 33  Sexual orientation_Unreported/Unknown               54584 non-null  int64
 34  Race/Hispanic ethnicity_Asian                       54584 non-null  int64
 35  Race/Hispanic ethnicity_Black                       54584 non-null  int64
 36  Race/Hispanic ethnicity_Hispanic                    54584 non-null  int64
 37  Race/Hispanic ethnicity_Other                       54584 non-null  int64
 38  Race/Hispanic ethnicity_White                       54584 non-null  int64
 39  Marriage status_Divorced                            54584 non-null  int64
 40  Marriage status_Never married                       54584 non-null  int64
 41  Marriage status_Now married                         54584 non-null  int64
 42  Marriage status_Separated                           54584 non-null  int64
 43  Marriage status_Unreported/Unknown                  54584 non-null  int64
 44  Marriage status_Widowed                             54584 non-null  int64
 45  Price Change_Decreased                              54584 non-null  int64
 46  Price Change_Increased                              54584 non-null  int64
 47  Price Change_Not changed                            54584 non-null  int64
 48  Price Change_Unreported/Unknown                     54584 non-null  int64
 49  Price Stress_A little stressful                     54584 non-null  int64
 50  Price Stress_Moderately stressful                   54584 non-null  int64
 51  Price Stress_Not at all stressful                   54584 non-null  int64
 52  Price Stress_Unreported/Unknown                     54584 non-null  int64
 53  Price Stress_Very stressful                         54584 non-null  int64
 54  Accommodation_Fully Owned                           54584 non-null  int64
 55  Accommodation_Occupied without rent                 54584 non-null  int64
 56  Accommodation_Owned with mortgage                   54584 non-null  int64
 57  Accommodation_Rented                                54584 non-null  int64
 58  Accommodation_Unreported/Unknown                    54584 non-null  int64
 59  Food Supply_Enough Food                             54584 non-null  int64
 60  Food Supply_Often Not Enough                        54584 non-null  int64
 61  Food Supply_Sometimes Not Enough                    54584 non-null  int64
 62  Food Supply_Unreported/Unknown                      54584 non-null  int64
 63  Active Duty_No                                      54584 non-null  int64
 64  Active Duty_On Active Duty                          54584 non-null  int64
 65  Active Duty_Spouse On Active Duty                   54584 non-null  int64
 66  Active Duty_Unreported/Unknown                      54584 non-null  int64
 67  Veteran_No                                          54584 non-null  int64
 68  Veteran_Served Active Duty                          54584 non-null  int64
 69  Veteran_Spouse Served Active Duty                   54584 non-null  int64
 70  Veteran_Unreported/Unknown                          54584 non-null  int64
dtypes: float64(4), int64(65), object(2)
memory usage: 30.0+ MB

<div style="border-radius:10px; border: #B0E0E6 solid; padding: 15px; background-color: #F0F8FF; font-size:100%; text-align:left">
<font size="2px" color="#000000"> 
    <b>Comment</b>: With all our categorical columns now converted into numerical representations, we are ready to move forward by removing the reference columns from our dataset.
<div>

#### **3.8 Get rid of reference columns**

In [73]:
#get the reference columns
reference_categories = ['Work Loss_Unreported/Unknown ','Any Work_Unreported/Unknown ','Unemployment Insurance Receive_Unreported/Unknown ','Had Covid-19_Unreported/Unknown','Covid Vaccinated_Unreported/Unknown','Gender Identity_Unreported/Unknown','Sexual orientation_Unreported/Unknown','Marriage status_Unreported/Unknown','Price Change_Unreported/Unknown','Price Stress_Unreported/Unknown','Accommodation_Unreported/Unknown','Food Supply_Unreported/Unknown','Active Duty_Unreported/Unknown','Veteran_Unreported/Unknown']

#drop the reference columns
df_with_dummies.drop(columns=reference_categories, inplace=True)

In [74]:
#sanity check
df_with_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54584 entries, V610000001 to V610068454
Data columns (total 57 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Education                            54584 non-null  float64
 1   Total People                         54584 non-null  int64
 2   Total Children                       54584 non-null  int64
 3   Income                               54584 non-null  float64
 4   Food Spend                           54584 non-null  float64
 5   Medical Shortage                     54584 non-null  int64
 6   Depression                           54584 non-null  object
 7   Anxiety                              54584 non-null  object
 8   Age Generation                       54584 non-null  float64
 9   Work Loss_No                         54584 non-null  int64
 10  Work Loss_Yes                        54584 non-null  int64
 11  Any Work_No                          54584 non-null  int64
 12  Any Work_Yes                         54584 non-null  int64
 13  Unemployment Insurance Receive_No    54584 non-null  int64
 14  Unemployment Insurance Receive_Yes   54584 non-null  int64
 15  Had Covid-19_No                      54584 non-null  int64
 16  Had Covid-19_Yes                     54584 non-null  int64
 17  Covid Vaccinated_No                  54584 non-null  int64
 18  Covid Vaccinated_Yes                 54584 non-null  int64
 19  Gender Identity_Female               54584 non-null  int64
 20  Gender Identity_Male                 54584 non-null  int64
 21  Gender Identity_None of these        54584 non-null  int64
 22  Gender Identity_Transgender          54584 non-null  int64
 23  Sexual orientation_Bisexual          54584 non-null  int64
 24  Sexual orientation_Gay or lesbian    54584 non-null  int64
 25  Sexual orientation_Something else    54584 non-null  int64
 26  Sexual orientation_Straight          54584 non-null  int64
 27  Race/Hispanic ethnicity_Asian        54584 non-null  int64
 28  Race/Hispanic ethnicity_Black        54584 non-null  int64
 29  Race/Hispanic ethnicity_Hispanic     54584 non-null  int64
 30  Race/Hispanic ethnicity_Other        54584 non-null  int64
 31  Race/Hispanic ethnicity_White        54584 non-null  int64
 32  Marriage status_Divorced             54584 non-null  int64
 33  Marriage status_Never married        54584 non-null  int64
 34  Marriage status_Now married          54584 non-null  int64
 35  Marriage status_Separated            54584 non-null  int64
 36  Marriage status_Widowed              54584 non-null  int64
 37  Price Change_Decreased               54584 non-null  int64
 38  Price Change_Increased               54584 non-null  int64
 39  Price Change_Not changed             54584 non-null  int64
 40  Price Stress_A little stressful      54584 non-null  int64
 41  Price Stress_Moderately stressful    54584 non-null  int64
 42  Price Stress_Not at all stressful    54584 non-null  int64
 43  Price Stress_Very stressful          54584 non-null  int64
 44  Accommodation_Fully Owned            54584 non-null  int64
 45  Accommodation_Occupied without rent  54584 non-null  int64
 46  Accommodation_Owned with mortgage    54584 non-null  int64
 47  Accommodation_Rented                 54584 non-null  int64
 48  Food Supply_Enough Food              54584 non-null  int64
 49  Food Supply_Often Not Enough         54584 non-null  int64
 50  Food Supply_Sometimes Not Enough     54584 non-null  int64
 51  Active Duty_No                       54584 non-null  int64
 52  Active Duty_On Active Duty           54584 non-null  int64
 53  Active Duty_Spouse On Active Duty    54584 non-null  int64
 54  Veteran_No                           54584 non-null  int64
 55  Veteran_Served Active Duty           54584 non-null  int64
 56  Veteran_Spouse Served Active Duty    54584 non-null  int64
dtypes: float64(4), int64(51), object(2)
memory usage: 24.2+ MB

In [75]:
df_with_dummies.drop(columns='Race/Hispanic ethnicity_Other',inplace=True)

df_with_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54584 entries, V610000001 to V610068454
Data columns (total 56 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Education                            54584 non-null  float64
 1   Total People                         54584 non-null  int64
 2   Total Children                       54584 non-null  int64
 3   Income                               54584 non-null  float64
 4   Food Spend                           54584 non-null  float64
 5   Medical Shortage                     54584 non-null  int64
 6   Depression                           54584 non-null  object
 7   Anxiety                              54584 non-null  object
 8   Age Generation                       54584 non-null  float64
 9   Work Loss_No                         54584 non-null  int64
 10  Work Loss_Yes                        54584 non-null  int64
 11  Any Work_No                          54584 non-null  int64
 12  Any Work_Yes                         54584 non-null  int64
 13  Unemployment Insurance Receive_No    54584 non-null  int64
 14  Unemployment Insurance Receive_Yes   54584 non-null  int64
 15  Had Covid-19_No                      54584 non-null  int64
 16  Had Covid-19_Yes                     54584 non-null  int64
 17  Covid Vaccinated_No                  54584 non-null  int64
 18  Covid Vaccinated_Yes                 54584 non-null  int64
 19  Gender Identity_Female               54584 non-null  int64
 20  Gender Identity_Male                 54584 non-null  int64
 21  Gender Identity_None of these        54584 non-null  int64
 22  Gender Identity_Transgender          54584 non-null  int64
 23  Sexual orientation_Bisexual          54584 non-null  int64
 24  Sexual orientation_Gay or lesbian    54584 non-null  int64
 25  Sexual orientation_Something else    54584 non-null  int64
 26  Sexual orientation_Straight          54584 non-null  int64
 27  Race/Hispanic ethnicity_Asian        54584 non-null  int64
 28  Race/Hispanic ethnicity_Black        54584 non-null  int64
 29  Race/Hispanic ethnicity_Hispanic     54584 non-null  int64
 30  Race/Hispanic ethnicity_White        54584 non-null  int64
 31  Marriage status_Divorced             54584 non-null  int64
 32  Marriage status_Never married        54584 non-null  int64
 33  Marriage status_Now married          54584 non-null  int64
 34  Marriage status_Separated            54584 non-null  int64
 35  Marriage status_Widowed              54584 non-null  int64
 36  Price Change_Decreased               54584 non-null  int64
 37  Price Change_Increased               54584 non-null  int64
 38  Price Change_Not changed             54584 non-null  int64
 39  Price Stress_A little stressful      54584 non-null  int64
 40  Price Stress_Moderately stressful    54584 non-null  int64
 41  Price Stress_Not at all stressful    54584 non-null  int64
 42  Price Stress_Very stressful          54584 non-null  int64
 43  Accommodation_Fully Owned            54584 non-null  int64
 44  Accommodation_Occupied without rent  54584 non-null  int64
 45  Accommodation_Owned with mortgage    54584 non-null  int64
 46  Accommodation_Rented                 54584 non-null  int64
 47  Food Supply_Enough Food              54584 non-null  int64
 48  Food Supply_Often Not Enough         54584 non-null  int64
 49  Food Supply_Sometimes Not Enough     54584 non-null  int64
 50  Active Duty_No                       54584 non-null  int64
 51  Active Duty_On Active Duty           54584 non-null  int64
 52  Active Duty_Spouse On Active Duty    54584 non-null  int64
 53  Veteran_No                           54584 non-null  int64
 54  Veteran_Served Active Duty           54584 non-null  int64
 55  Veteran_Spouse Served Active Duty    54584 non-null  int64
dtypes: float64(4), int64(50), object(2)
memory usage: 23.7+ MB

#### **3.9 Export data for modelling**

In [76]:
df_with_dummies.to_csv('/Users/kouyuyang/Brainstation/Capstone/Sprint 2/Feature Engineering Data.csv', index=False)